# profile: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.64.3:3306/webdb?characterEncoding=utf8
      username: webdb
      password: '{cipher}AYAiRuOOu6r96qyaj6eFZ14uZlGW17zJPgGcEclITZzopKRxsYqpp1GrWsbSaljUk2kA5QrJdz/guQmRWqoPIxHE2D8IsrXbQH0xi5BaBYyYkVJLLNFBgP7e+AgG9Lrv+jpBva1YimL2aV/e86j2JDlK6L6t6HxsDJ8cV2p/dtNWHqNkWyGZ8Rc/GavNGHF5PgZwUBKk/zUxbtw25vH8w2Zmlpn792X6blP3XY5/TVyV4bBM3CW7QizigZF+i83XwugfOM8zEHHD84tijeTeX/M/RzcgjDuEBEYTER3bXN9z1+Zdy7G8axaGmM5BVuo75Wgl3hCmu3eUOmG4ZotykSqrahIJOrpVJHaN+BPpjattJbvsTsF3dzw0BKv2DBgXbufLozcpPPk9PMdDkY5PfFAaqzqwwwHGmJ3dFfwLs/52BVm+GOd+PyLRXfCqgMHWQME6K6mItpxRHOoYXqXGkwNpARU8DzMP20puX1/5EWHwadIrL4qiyg1Tm+SSB5CxQo3SozkCMaiQirWFDG/tz6L9R12eO9czUXQbOjKP6CLWvg=='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20 

eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.64.3:8761/eureka

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      emaillist:
         exception: ERROR