# profile: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.64.3:3306/webdb?characterEncoding=utf8
      username: webdb
      password: '{cipher}AYAlD6VrwWQgVoR3LROv8pjU0tZYdehNWXgcBocKIwBvO7h8sOyANr43JMtt29jQvR66w92hlCbEIMFyxVVoiKouqpmx5jLv4IfhQQ4KKquZuC705o6aSqWiRpLzirRMlh07GH4qSA5vlbAMfjVwJmTLdtzdwOFe1xpmRCr/PiZtRyWmHW9zACWro/kqfU1cxF9iYVa8ZvZhQO+Hp/esaoLNlO8lzajo3liTsteF3WKQZqrkPxrw56xTmkMysZPYKUd7I6ggbplwt+Qg5Q2WcCT1PXNe9Q/WVY54raiw/8CDAFn2YWhanXa4VDnUHgHaZy1nYZT09BOzdBYRSygdGhqSrlDXYTgirvgpkVMzWqhoHFUQPJtcZXXAjhQQ/2Vk+3Zq4auue/zYvWWgxPDWBnJy5++k7VZM/q0P5+hd8hLR5bdyvxG/A04oR9m59UG9ETWJwxAcPK5xFaBMapJPVtQN11vxn8nrDvYdiG7l/GoQOw/wh5PAk10+/Qy58l+8gOFcqk9rxIFtX8OzQpLStpG75V51LFqVU7gJkHEBkIPcKg=='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20 

eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.64.3:8761/eureka

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      emaillist:
         exception: ERROR